#Discord
DISCORD_BOT_TOKEN = 'YOUR_DISCORD_BOT_TOKEN'

#Twitter
TWITTER_API_KEY = ''
TWITTER_API_SECRET_KEY = ''
TWITTER_ACCESS_TOKEN = ''
TWITTER_ACCESS_TOKEN_SECRET = ''

# Add your Discord channel IDs here
DISCORD_CHANNEL_IDS = [1076202500597760141]